### ISSUE TITLE
Error while using gpg

### ISSUE THREAD

**Issue by tedgonzalez** [martianplatypus/ansible-role-ruby-mac#14]
Hi @martianplatypus, thanks for sharing this awesome role!
Can you give me some tips regarding this issue?
I'm having an error when running via role:
```
- name: Install ruby and gems
  hosts: all
  vars:
    make_default_ruby: false
    ruby_version: 2.6.6
    gems:
      - bundler
      - fastlane
  roles:
    - role: martianplatypus.ruby_mac
```
I get this:
```
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB", "failed_when_result": true, "msg": "[Errno 2] No such file or directory", "rc": 2}
```
When running locally, this is what I get:
```
gpg: key 105BD0E739499BDB: "Piotr Kuczynski <piotr.kuczynski@gmail.com>" not changed
gpg: key 3804BB82D39DC0E3: "Michal Papis (RVM signing) <mpapis@gmail.com>" not changed
gpg: Total number processed: 2
gpg:              unchanged: 2
```

I also tried setting:
```gpg_keyserver: "hkp://ipv4.pool.sks-keyservers.net"```
